export const DUMMY_USERS = [
  {
    id: 'v1',
    name: 'Juliusz Buzzing',
    location: 'Dalkey, Ireland',
    date: '2023-06-01',
    thumbnail: 'user-1.jpg',
    filePath: 'juliusz',
    format: 'mp4',
  },
  {
    id: 'v2',
    name: 'Juliusz Buzzing',
    location: 'Dalkey, Ireland',
    date: '2023-06-01',
    thumbnail: 'user-1.jpg',
    filePath: 'juliusz',
    format: 'mp4',
  },
  {
    id: 'v3',
    name: 'Juliusz Buzzing',
    location: 'Dalkey, Ireland',
    date: '2023-06-01',
    thumbnail: 'user-1.jpg',
    filePath: 'juliusz',
    format: 'mp4',
  },
  {
    id: 'v4',
    name: 'Juliusz Buzzing',
    location: 'Dalkey, Ireland',
    date: '2023-06-01',
    thumbnail: 'user-1.jpg',
    filePath: 'juliusz',
    format: 'mp4',
  },
  {
    id: 'v5',
    name: 'Juliusz Buzzing',
    location: 'Dalkey, Ireland',
    date: '2023-06-01',
    thumbnail: 'user-1.jpg',
    filePath: 'juliusz',
    format: 'mp4',
  },
  {
    id: 'v6',
    name: 'Juliusz Buzzing',
    location: 'Dalkey, Ireland',
    date: '2023-06-01',
    thumbnail: 'user-1.jpg',
    filePath: 'juliusz',
    format: 'mp4',
  },
  {
    id: 'v7',
    name: 'Juliusz Buzzing',
    location: 'Dalkey, Ireland',
    date: '2023-06-01',
    thumbnail: 'user-1.jpg',
    filePath: 'juliusz',
    format: 'mp4',
  },
  {
    id: 'v8',
    name: 'Juliusz Buzzing',
    location: 'Dalkey, Ireland',
    date: '2023-06-01',
    thumbnail: 'user-1.jpg',
    filePath: 'juliusz',
    format: 'mp4',
  },
  {
    id: 'v9',
    name: 'Juliusz Buzzing',
    location: 'Dalkey, Ireland',
    date: '2023-06-01',
    thumbnail: 'user-1.jpg',
    filePath: 'juliusz',
    format: 'mp4',
  },
];
